#!/usr/bin/env python3

# bspwmrc is a shell script, by filtering out non-bspwm related lines we can
# simply rerun the script at runtime to apply changes.
# no idea why this isn't part of the wm

from sys import argv
from os import environ
from subprocess import call

def main():
    bspwmrc = argv[1] if (len(argv) > 1) else environ['HOME'] + '/.config/bspwm/bspwmrc' # I miss C

    with open(bspwmrc) as configFile: # see, thats smart
        for line in configFile:
            if not line.startswith('bspc'):
                continue # avoid autostart lines and bspwm unrelated commands
            line.rstrip('\n') # get rid of newline characters
            line = line.replace("\\", "") # this avoid double escaping
            call(line.split())

if __name__ == '__main__':
    main()
